[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

[rpc_endpoints]
bsc = 'https://rpc.bolide.fi/bsc'
polygon = 'https://rpc.bolide.fi/polygon'
mainnet = 'https://rpc.ankr.com/eth'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config